# Generated by Django 5.2.1 on 2025-05-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=25, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=25, verbose_name="Last Name"),
                ),
                ("gender", models.CharField(max_length=5, verbose_name="Gender")),
                (
                    "papers",
                    models.ManyToManyField(
                        to="subjects.paper", verbose_name="Papers taught"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.school",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
            },
        ),
    ]
