# Generated by Django 5.2.1 on 2025-06-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_teacher_userprofile_phone_2_and_more"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
    ]
