# Generated by Django 5.2.1 on 2025-06-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_class_options"),
        ("streams", "0005_alter_stream_class_teacher"),
        ("subjects", "0008_alter_subject_options"),
        ("teachers", "0002_delete_teacher_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_assignments",
                        to="classes.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teaching_assignments",
                        to="subjects.paper",
                        verbose_name="Papers",
                    ),
                ),
                (
                    "streams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teaching_assignments",
                        to="streams.stream",
                        verbose_name="Streams",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subject",
                        verbose_name="Subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.teacher",
                        verbose_name="Teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "teaching assignment",
                "verbose_name_plural": "teaching assignments",
            },
        ),
    ]
