# Generated by Django 5.2.1 on 2025-06-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
        ("teachers", "0003_teachingassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachingassignment",
            name="papers",
        ),
        migrations.RemoveField(
            model_name="teachingassignment",
            name="teacher",
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.school",
                verbose_name="School",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="teachers",
            field=models.ManyToManyField(
                related_name="teaching_assignments",
                to="teachers.teacher",
                verbose_name="Teacher",
            ),
        ),
    ]
