# Generated by Django 5.2.1 on 2025-06-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_class_options"),
        ("schools", "0002_initial"),
        ("subjects", "0008_alter_subject_options"),
        ("teachers", "0004_remove_teachingassignment_papers_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teachingassignment",
            unique_together={("subject", "class_group", "school")},
        ),
    ]
