# Generated by Django 5.2.1 on 2025-06-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
        ("subjects", "0008_alter_subject_options"),
        ("teachers", "0005_alter_teachingassignment_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teachingassignment",
            unique_together={("subject", "school")},
        ),
        migrations.RemoveField(
            model_name="teachingassignment",
            name="class_group",
        ),
        migrations.RemoveField(
            model_name="teachingassignment",
            name="streams",
        ),
    ]
