# Generated by Django 5.2.1 on 2025-06-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0005_alter_stream_class_teacher"),
        ("teachers", "0006_alter_teachingassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingassignment",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_assignments",
                to="streams.stream",
                verbose_name="Streams",
            ),
            preserve_default=False,
        ),
    ]
