# Generated by Django 5.2.1 on 2025-06-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
        ("streams", "0005_alter_stream_class_teacher"),
        ("subjects", "0008_alter_subject_options"),
        ("teachers", "0007_teachingassignment_stream"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teachingassignment",
            unique_together={("subject", "school", "stream")},
        ),
    ]
