# Generated by Django 5.2.1 on 2025-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=25, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=25, verbose_name="Last Name"),
                ),
                ("gender", models.CharField(max_length=5, verbose_name="Gender")),
                (
                    "primary_role",
                    models.CharField(
                        choices=[
                            ("Teacher", "Teacher"),
                            ("Administrator", "Administrator"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Primary Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staffs",
            },
        ),
    ]
