# Generated by Django 5.2.1 on 2025-05-26 17:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("periods", "0002_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.DecimalField(
                        choices=[
                            (Decimal("1"), "1"),
                            (Decimal("2"), "2"),
                            (Decimal("3"), "3"),
                        ],
                        decimal_places=0,
                        max_digits=1,
                        verbose_name="Number",
                    ),
                ),
                (
                    "registered_students",
                    models.ManyToManyField(related_name="terms", to="students.student"),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="periods.year",
                        verbose_name="Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term",
                "verbose_name_plural": "Terms",
                "ordering": ["year", "number"],
                "unique_together": {("number", "year")},
            },
        ),
    ]
