# Generated by Django 5.2.1 on 2025-05-29 14:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.DecimalField(
                        choices=[
                            (Decimal("1"), "1"),
                            (Decimal("2"), "2"),
                            (Decimal("3"), "3"),
                        ],
                        decimal_places=0,
                        max_digits=1,
                        verbose_name="Number",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(unique=True, verbose_name="Start Date"),
                ),
                ("end_date", models.DateField(unique=True, verbose_name="End Date")),
                ("fees", models.PositiveIntegerField(default=0, verbose_name="Fees")),
                (
                    "registered_students",
                    models.ManyToManyField(related_name="terms", to="students.student"),
                ),
            ],
            options={
                "verbose_name": "Term",
                "verbose_name_plural": "Terms",
                "ordering": ["start_date"],
                "unique_together": {("number", "start_date")},
            },
        ),
    ]
