# Generated by Django 5.2.1 on 2025-05-29 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Term",
                "verbose_name_plural": "Terms",
            },
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("number", "start_date")},
        ),
        migrations.AddField(
            model_name="term",
            name="end_date",
            field=models.DateField(
                default=datetime.date(2025, 5, 29), unique=True, verbose_name="End Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="term",
            name="fees",
            field=models.PositiveIntegerField(default=0, verbose_name="Fees"),
        ),
        migrations.AddField(
            model_name="term",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2025, 5, 29),
                unique=True,
                verbose_name="Start Date",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="term",
            name="year",
        ),
    ]
