# Generated by Django 5.2.1 on 2025-05-30 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="term",
            name="fees",
        ),
        migrations.RemoveField(
            model_name="term",
            name="registered_students",
        ),
        migrations.CreateModel(
            name="TermFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=0, verbose_name="Amount"),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True, related_name="term_fees", to="classes.class"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="terms.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term Fee",
                "verbose_name_plural": "Term Fees",
            },
        ),
    ]
