# Generated by Django 5.2.1 on 2025-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0002_remove_term_fees_remove_term_registered_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
