# Generated by Django 5.2.1 on 2025-05-31 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
        ("terms", "0003_term_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms",
                to="schools.school",
                verbose_name="School",
            ),
            preserve_default=False,
        ),
    ]
