# Generated by Django 5.2.1 on 2025-05-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("tiers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="tier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="tiers.tier",
                verbose_name="Tier",
            ),
        ),
    ]
