# Generated by Django 5.2.1 on 2025-05-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Short Name"
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="registration_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Reg no.",
            ),
        ),
    ]
