# Generated by Django 5.2.1 on 2025-06-10 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0008_alter_subject_options"),
        ("terms", "0004_term_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "competency",
                    models.TextField(blank=True, null=True, verbose_name="Competency"),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "total_mark",
                    models.PositiveSmallIntegerField(verbose_name="Total Mark"),
                ),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True, to="subjects.paper", verbose_name="Papers"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subject",
                        verbose_name="Subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="terms.term",
                        verbose_name="Term",
                    ),
                ),
            ],
            options={
                "verbose_name": "assessment",
                "verbose_name_plural": "assessments",
            },
        ),
    ]
