# Generated by Django 5.2.1 on 2025-06-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("classes", "0002_alter_class_options"),
        ("subjects", "0008_alter_subject_options"),
        ("terms", "0004_term_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="cls",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.class",
                verbose_name="Class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessment",
            name="kind",
            field=models.CharField(
                choices=[("CA", "Continuous Assessment"), ("EX", "Examination")],
                default="CA",
                max_length=5,
                verbose_name="Kind",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="assessment",
            unique_together={("order", "term", "subject", "cls")},
        ),
    ]
