# Generated by Django 5.2.1 on 2025-05-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollment", "0001_initial"),
        ("streams", "0001_initial"),
        ("students", "0001_initial"),
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="streams.stream",
                verbose_name="Stream",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="terms.term",
                verbose_name="Term",
            ),
        ),
    ]
