# Generated by Django 5.2.1 on 2025-05-31 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("enrollment", "0002_initial"),
        ("streams", "0002_alter_stream_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="stream",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="class_for",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.class",
                verbose_name="Class enrolled for.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="stream_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="streams.stream",
                verbose_name="Stream enrolled for.",
            ),
        ),
    ]
