# Generated by Django 5.2.1 on 2025-06-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0003_remove_enrollment_stream_enrollment_class_for_and_more"),
        ("streams", "0002_alter_stream_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="stream_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="streams.stream",
                verbose_name="Stream enrolled for.",
            ),
        ),
    ]
