# Generated by Django 5.2.1 on 2025-06-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0004_alter_enrollment_stream_for"),
        ("terms", "0004_term_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="terms.term",
                verbose_name="Term",
            ),
        ),
    ]
