# Generated by Django 5.2.1 on 2025-06-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="Is Teacher"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone (Other)"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_1",
            field=models.CharField(max_length=20, verbose_name="Phone (Main)"),
        ),
    ]
