# Generated by Django 5.2.1 on 2025-05-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_first_name_user_last_name_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="_is_school_owner",
            new_name="is_school_owner",
        ),
    ]
