# Generated by Django 5.2.1 on 2025-06-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_profile_remove_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("has_teacher_role", "Has Teacher Role")],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
