# Generated by Django 5.2.1 on 2025-05-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
        ("streams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="schools.school",
                verbose_name="School",
            ),
        ),
    ]
