# Generated by Django 5.2.1 on 2025-06-02 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("streams", "0002_alter_stream_school"),
        ("teachers", "0002_delete_teacher_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="current_class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="streams",
                to="teachers.teacher",
                verbose_name="Current Class Teacher",
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="current_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="classes.class",
                verbose_name="Class",
            ),
        ),
    ]
