# Generated by Django 5.2.1 on 2025-06-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0003_stream_current_class_teacher_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stream",
            old_name="current_class_teacher",
            new_name="class_teacher",
        ),
    ]
