# Generated by Django 5.2.1 on 2025-06-10 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0004_rename_current_class_teacher_stream_class_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="streams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Current Class Teacher",
            ),
        ),
    ]
