# Generated by Django 5.2.1 on 2025-05-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parents", "0001_initial"),
        ("schools", "0001_initial"),
        ("streams", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date added to system"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=25, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=25, verbose_name="Last Name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "payment_code",
                    models.CharField(max_length=50, verbose_name="Payment Code"),
                ),
                (
                    "current_optional_papers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="current_students",
                        to="subjects.paper",
                        verbose_name="Optional Papers",
                    ),
                ),
                (
                    "current_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_students",
                        to="streams.stream",
                        verbose_name="Current Stream",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                        ],
                        default="mother",
                        max_length=50,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students_relations",
                        to="parents.parent",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relations",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "StudentParent",
                "verbose_name_plural": "StudentParents",
                "unique_together": {("student", "parent")},
            },
        ),
    ]
