# Generated by Django 5.2.1 on 2025-05-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="current_stream",
        ),
    ]
