# Generated by Django 5.2.1 on 2025-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
        ("students", "0002_remove_student_current_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("school", "payment_code")},
        ),
    ]
