# Generated by Django 5.2.1 on 2025-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_active_alter_student_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="lin",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Learners Identification Number",
            ),
        ),
    ]
