# Generated by Django 5.2.1 on 2025-05-26 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (2025, "2025"),
                            (2024, "2024"),
                            (2023, "2023"),
                            (2022, "2022"),
                            (2021, "2021"),
                            (2020, "2020"),
                            (2019, "2019"),
                            (2018, "2018"),
                            (2017, "2017"),
                            (2016, "2016"),
                            (2015, "2015"),
                            (2014, "2014"),
                            (2013, "2013"),
                            (2012, "2012"),
                            (2011, "2011"),
                            (2010, "2010"),
                        ],
                        default=2025,
                        validators=[
                            django.core.validators.MinValueValidator(2010),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                        verbose_name="Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-year"],
                "get_latest_by": "year",
            },
        ),
    ]
