# Generated by Django 5.2.1 on 2025-05-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("periods", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="year",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="schools.school"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="year",
            unique_together={("year", "school")},
        ),
    ]
