# Generated by Django 5.2.1 on 2025-06-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"permissions": [("can_manage_classes", "Can manage classes")]},
        ),
    ]
