# Generated by Django 5.2.1 on 2025-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Order of the tier in the list",
                        null=True,
                        unique=True,
                        verbose_name="Order",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Price of the tier",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="auth.permission", verbose_name="Permissions"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier",
                "verbose_name_plural": "Tiers",
                "ordering": ["order"],
            },
        ),
    ]
