# Generated by Django 5.2.1 on 2025-05-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=2, verbose_name="Number")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper",
                "verbose_name_plural": "Papers",
            },
        ),
        migrations.CreateModel(
            name="SchoolPapersGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="school_papers_groups",
                        to="subjects.paper",
                        verbose_name="Papers",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "SchoolPapersGroup",
                "verbose_name_plural": "SchoolPapersGroups",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Abbreviation"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="Code"),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[("O", "Ordinary"), ("A", "Advanced")],
                        max_length=1,
                        null=True,
                        verbose_name="Level",
                    ),
                ),
                (
                    "is_base",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a base subject?",
                        verbose_name="Is Base",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a default subject?",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="subjects.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subjects",
                        to="classes.class",
                        verbose_name="Classes",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.AddField(
            model_name="paper",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to="subjects.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paper",
            unique_together={("subject", "number")},
        ),
    ]
