# Generated by Django 5.2.1 on 2025-05-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_school_short_name_alter_school_registration_number"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolPapersGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="school_papers_groups",
                        to="subjects.paper",
                        verbose_name="Papers",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "SchoolPapersGroup",
                "verbose_name_plural": "SchoolPapersGroups",
            },
        ),
    ]
