# Generated by Django 5.2.1 on 2025-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpapersgroup",
            name="classes",
            field=models.ManyToManyField(
                related_name="paper_groups", to="classes.class", verbose_name="Classes"
            ),
        ),
    ]
