# Generated by Django 5.2.1 on 2025-06-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
        ("subjects", "0002_schoolpapersgroup_classes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolpapersgroup",
            name="classes",
        ),
        migrations.AlterField(
            model_name="schoolpapersgroup",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_groups",
                to="schools.school",
                verbose_name="School",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=4, unique=True, verbose_name="Code"),
        ),
    ]
