# Generated by Django 5.2.1 on 2025-05-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_schoolpapersgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Is this a default subject?",
                verbose_name="Is Default",
            ),
        ),
    ]
