# Generated by Django 5.2.1 on 2025-06-02 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
        ("subjects", "0003_remove_schoolpapersgroup_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="schoolpapersgroup",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_group",
                to="schools.school",
                verbose_name="School",
            ),
        ),
    ]
