# Generated by Django 5.2.1 on 2025-06-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0004_alter_paper_name_alter_schoolpapersgroup_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolpapersgroup",
            name="papers",
        ),
        migrations.CreateModel(
            name="SchoolPaperAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_compulsory",
                    models.BooleanField(default=False, verbose_name="Is Compulsory"),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_assignments",
                        to="subjects.paper",
                    ),
                ),
                (
                    "school_papers_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_assignments",
                        to="subjects.schoolpapersgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Paper Assignment",
                "verbose_name_plural": "School Paper Assignments",
                "unique_together": {("school_papers_group", "paper")},
            },
        ),
        migrations.AddField(
            model_name="schoolpapersgroup",
            name="papers_allowed",
            field=models.ManyToManyField(
                blank=True,
                related_name="school_papers_groups",
                through="subjects.SchoolPaperAssignment",
                through_fields=("school_papers_group", "paper"),
                to="subjects.paper",
                verbose_name="Papers",
            ),
        ),
    ]
