# Generated by Django 5.2.1 on 2025-06-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0005_remove_schoolpapersgroup_papers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schoolpapersgroup",
            old_name="papers_allowed",
            new_name="papers",
        ),
    ]
