# Generated by Django 5.2.1 on 2025-06-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0006_rename_papers_allowed_schoolpapersgroup_papers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
    ]
