# Generated by Django 5.2.1 on 2025-06-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0007_alter_paper_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "permissions": [("can_manage_all_subjects", "Can manage all subjects")],
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
    ]
