# Generated by Django 5.2.1 on 2025-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=25, verbose_name="Full Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="Phone")),
                (
                    "phone_2",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Phone 2"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
            ],
            options={
                "verbose_name": "parent",
                "verbose_name_plural": "parents",
            },
        ),
    ]
